config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "search_results#new"

  resources :search_results, except: [:edit, :update, :create]
  resources :link_queries, only: :index

  namespace :api do
    namespace :v1 do
      resource :search, only: :create
      resources :link_queries, only: :index
      resources :search_results, only: [:index, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :search_result

  enum link_type: [:non_ad, :top_ad, :bottom_ad]

  validates_presence_of :link_type, :title, :url
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :user
  has_many :links, dependent: :destroy, inverse_of: :search_result

  validates_presence_of :keyword, :total_results, :total_links, :html_code,
    :server_ip, :user_agent
  validates :keyword, uniqueness: true

  accepts_nested_attributes_for :links, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :search_results, dependent: :destroy
  has_many :access_grants, class_name: "Doorkeeper::AccessGrant",
                           foreign_key: :resource_owner_id,
                           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens, class_name: "Doorkeeper::AccessToken",
                           foreign_key: :resource_owner_id,
                           dependent: :delete_all # or :destroy if you need callbacks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  class << self
    def from_omniauth auth_hash
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.email = auth_hash['info']['email']
      user.password = Devise.friendly_token[0,20]
      user.save!
      user
    end
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  include Pundit
  before_action :doorkeeper_authorize!, :unless => :user_signed_in?

  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end

  def pundit_user
    current_resource_owner
  end
end

app/controllers/api/v1/link_queries_controller.rb
class Api::V1::LinkQueriesController < Api::V1::ApiController
  before_action :check_param_type, :check_param_keyword
  def index
    render json: load_links
  end

  private
  def check_param_type
    return if ["adword_url_contains", "specific_url", "string_occurs"].include? params[:type]
    render json: {message: "Invalid type"}, status: 400
  end

  def check_param_keyword
    return if params[:keyword].present?
    render json: {message: "Empty keyword"}, status: 400
  end

  def load_links
    LinksQuery.new.query params[:type], params[:keyword]
  end
end

app/controllers/api/v1/search_results_controller.rb
class Api::V1::SearchResultsController < Api::V1::ApiController
  before_action :load_search_results, only: :index
  before_action :load_search_result, only: :show

  def index
    render json: @search_results
  end

  def show
    render json: @search_result, detail: true
  end

  private
  def load_search_results
    @search_results = policy_scope(SearchResult).includes(:user).order(:keyword).page(params[:page]).per(Settings.pagination.per_page)
  end

  def load_search_result
    @search_result = policy_scope(SearchResult).includes(:user, :links).find_by id: params[:id]
  end
end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < Api::V1::ApiController
  def create
    case true
    when params[:keywords_file].present?
      begin
        CsvProcessingService.perform params[:keywords_file].path, current_user.id
        message, status = "The file is being processed", 200
      rescue Exception => e
        message, status = e.message, 400
      end
    when params[:keyword].present?
      search_result = ScraperService.new params[:keyword], current_user.id
      search_result.perform
      if search_result.error.empty?
        message, status = search_result.result.id, 200
      else
        message, status = search_result.error, 400
      end
    else
      message, status = "Invalid request", 400
    end
    render json: {message: message}, status: status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/link_queries_controller.rb
class LinkQueriesController < ApplicationController
  def index
  end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  before_action :load_search_result, except: :index

  def index
    @search_results = policy_scope(SearchResult).includes(:user).order(:keyword).page(params[:page]).per(Settings.pagination.per_page).decorate
  end

  def show
  end

  def new
  end

  def destroy
    if @search_result.destroy
      flash[:success] = "Delete successful"
    else
      flash[:danger] = "Delete failed"
    end
    redirect_to search_results_path
  end

  private
  def load_search_result
    @search_result = policy_scope(SearchResult).find_by(id: params[:id])&.decorate
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "Google Scraper"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def get_link_type_and_size links, link_type
    "#{link_type.to_s.humanize.pluralize}: #{links.size}"
  end

  def show_sidekiq_running_title
    if (runnung_keywords = Sidekiq::Stats.new.enqueued) > 0
      content_tag :div, class: "alert alert-warning" do
        content_tag :span, "The file is being processed. Please reload after few seconds"
      end
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Google Scraper", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Search results", search_results_path %></li>
          <li><%= link_to "Link queries", link_queries_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Profile", edit_user_registration_path %>
              </li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> fade in">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul><li><%= value %></li></ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= show_sidekiq_running_title %>
      <div class="flash-messages">
        <%= render "layouts/messages" %>
      </div>
      <%= yield %>
      <div class="col-md-12">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>

app/views/link_queries/index.html.erb
<% provide :title, "Link queries" %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Link queries</h2>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3>Some link queries</h3>
      </div>
      <%= form_tag api_v1_link_queries_path, id: "query-form", method: :get do %>
        <div class="panel-body">
          <div class="form-group">
            <label>Please choose:</label>
            <div class="form-check">
              <%= radio_button_tag :type, :adword_url_contains, true, class: "form-check-input" %>
              <label class="form-check-label" for="type_adword_url_contains">How many URLs contain the *keyword* in AdWords</label>
            </div>
            <div class="form-check">
              <%= radio_button_tag :type, :specific_url, false, class: "form-check-input" %>
              <label class="form-check-label" for="type_specific_url">How many times a specific *keyword* shows up in SEO.</label>
            </div>
            <div class="form-check">
              <%= radio_button_tag :type, :string_occurs, false, class: "form-check-input" %>
              <label class="form-check-label" for="type_string_occurs">How many links have URLs in SEO with {{string}} occurs from {{number}} times.</label><br>
              <span> Ex: <b>2+-</b>: '-' occurs greater or equal twice</span>
            </div>
            <div class="form-group">
              <label for="keyword">Keyword:</label>
                <%= text_field_tag :keyword, nil, class: "form-control" %>
              <span id="keyword"></span>
            </div>
          </div>
          <div class="form-group">
            <div class="alert alert-danger infoLinkQueries"></div>
          </div>
          <div class="form-group">
            <div class="alert alert-info infoLinkQueryResult"></div>
          </div>
        </div>
        <div class="panel-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/search_results/_code_modal.html.erb
<div class="modal fade" id="html-code-<%= search_result.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= search_result.html_code %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/search_results/_index.html.erb
<% @search_results.each do |search_result| %>
  <tr>
    <td><%= search_result.id %></td>
    <td><%= search_result.keyword_display %></td>
    <td><%= search_result.total_results_display %></td>
    <td><%= search_result.total_links %></td>
    <td><%= search_result.user.email %></td>
    <td>
      <%= link_to "Details", search_result_path(search_result),
        class: "btn btn-success" %>
      <%= link_to "Remove", search_result_path(search_result), method: :delete,
        data: {confirm: "Are you sure?"},
        class: "btn btn-danger" %>
    </td>
  </tr>
<% end %>

app/views/search_results/_links.html.erb
<ul class="list-group">
  <li class="list-group-item active"><%= get_link_type_and_size links, link_type %></li>
  <% links.each do |link| %>
    <li class="list-group-item">
      <%= "#{link.title} |" %>
      <%= link_to link.url, link.url %>
    </li>
  <% end %>
</ul>

app/views/search_results/index.html.erb
<% provide :title, "List search results" %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Search results
      <span class="pull-right">
        <%= link_to "New search", new_search_result_path,
          class: "btn btn-primary" %>
      </span>
    </h2>
    <table class="table table-hover table-bordered">
      <thead>
        <tr class="info">
          <th>ID</th>
          <th>Keyword</th>
          <th>Total results</th>
          <th>Total links (first page)</th>
          <th>Search by</th>
          <th>Actions</th>
        </tr>
      </thead>
      <%= render "index" %>
    </table>
    <%= paginate @search_results %>
  </div>
</div>

app/views/search_results/new.html.erb
<% provide :title, "New search result" %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>New search result</h2>
    <div class="row">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3>Upload Keywords File</h3>
        </div>
        <%= form_tag api_v1_search_path, id: "file-upload-form", method: :post do %>
          <div class="panel-body">
            <div class="form-group">
              <label for="keywords_file">Upload .csv File:</label>
                <%= file_field_tag :keywords_file, class: "form-control-file" %>
              <span id="keywords_file"></span>
            </div>
            <div class="form-group">
              <div class="alert alert-danger infoFileUploadForm"></div>
            </div>
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3>Search by keyword</h3>
        </div>
        <%= form_tag api_v1_search_path, id: "keyword-form", method: :post do %>
          <div class="panel-body">
            <div class="form-group">
              <label for="keyword">Keyword:</label>
                <%= text_field_tag :keyword, nil, class: "form-control" %>
              <span id="keyword"></span>
            </div>
            <div class="form-group">
              <div class="alert alert-danger infoKeywordForm"></div>
            </div>
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search_results/show.html.erb
<% provide :title, "Search result details" %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Search details</h2>
    <div class="panel panel-info">
      <div class="panel-heading">
        Keyword: <%= @search_result.keyword_display %>
        <span class="pull-right"><%= %></span>
      </div>
        <div class="panel-body">
          <ul class="list-group">
            <li class="list-group-item active">General information</li>
            <li class="list-group-item">
              <%= "Search by: #{@search_result.user.email}" %>
            </li>
            <li class="list-group-item">
              <%= "Total results: #{@search_result.total_results_display}" %>
            </li>
            <li class="list-group-item">
              <%= "Total result links in first page: #{@search_result.total_links}" %>
            </li>
          </ul>
          <ul class="list-group">
            <li class="list-group-item active">For server tracking</li>
            <li class="list-group-item">
              <%= "Server IP: #{@search_result.server_ip}" %>
            </li>
            <li class="list-group-item">
              <%= "UserAgent: #{@search_result.user_agent}" %>
            </li>
          </ul>
          <%= render "links", links: @search_result.links.top_ad, link_type: :top_ad %>
          <%= render "links", links: @search_result.links.bottom_ad, link_type: :bottom_ad %>
          <%= render "links", links: @search_result.links.non_ad, link_type: :non_ad %>
          <div class="jumbotron">
            <a class="btn btn-primary" data-toggle="collapse" href="#collapse-code" role="button" aria-expanded="false" aria-controls="collapse-code">Toggle HTML code</a>
            <div class="collapse" id="collapse-code">
              <div class="html-code">
                <%= @search_result.html_code.html_safe %>
              </div>
            </div>
          </div>
        </div>

        <div class="panel-footer">
          <div class="row">
            <div class="col-md-4">
              <%= link_to 'Back', :back,
                class: "btn btn-info" %>
            </div>
          </div>
    </div>
  </div>
</div>